# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Julia Partheymüller
email: julia.partheymueller@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Julia Partheymüller
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.juliapartheymueller.de" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md

menu:
  - index.html
  - cv.md
  - publications.md
  - teaching.md
  - data.md
  - about.md
